const data = window.UMROH_DATA;
const savedPackages = localStorage.getItem("andira_umroh_packages");
if (savedPackages) { try { data.departures = JSON.parse(savedPackages); } catch (_) {} }
const rupiah = value => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value).replace("Rp", "Rp ");
const compact = value => value >= 1e9 ? `Rp ${(value / 1e9).toFixed(2).replace('.', ',')} M` : `Rp ${(value / 1e6).toFixed(1).replace('.', ',')} jt`;
const formatDate = value => new Intl.DateTimeFormat("id-ID", { day:"numeric", month:"short", year:"numeric" }).format(new Date(`${value}T00:00:00`));

const el = id => document.getElementById(id);
function filteredDepartures() {
  const period = el("periodFilter").value;
  const status = el("statusFilter").value;
  return data.departures.filter(d => (period === "all" || String(d.id) === period) && (status === "all" || d.status === status));
}
function renderKPIs(items) {
  const total = items.reduce((s,d) => s + d.quota, 0), sold = items.reduce((s,d) => s + d.sold, 0), booking = items.reduce((s,d) => s + d.booking, 0);
  const cards = [
    ["Total Kuota", total, "kursi", "▦", "navy", `${items.length} keberangkatan aktif`],
    ["Jamaah Terjual", sold, "jamaah", "✓", "green", `${total ? Math.round(sold / total * 100) : 0}% dari total kuota`],
    ["Booking Aktif", booking, "jamaah", "◷", "amber", "Prospek siap konversi"],
    ["Sisa Kursi", Math.max(total-sold,0), "kursi", "◎", "blue", "Perlu dikejar tim sales"]
  ];
  el("kpiGrid").innerHTML = cards.map(c => `<article class="kpi-card"><div class="kpi-top"><span>${c[0]}</span><i class="kpi-icon ${c[4]}">${c[3]}</i></div><div class="kpi-value">${c[1]} <small>${c[2]}</small></div><div class="kpi-note"><b class="${c[4]}">${c[0] === 'Sisa Kursi' ? '→' : '↗'}</b>${c[5]}</div></article>`).join("");
}
function renderDepartures(items) {
  el("departuresTable").innerHTML = items.length ? items.map(d => { const p=Math.round(d.sold/d.quota*100); return `<tr><td><strong>${d.name}</strong><small>${formatDate(d.date)}</small></td><td>${d.quota}</td><td><strong>${d.sold}</strong><small>+ ${d.booking} booking</small></td><td><div class="progress-row"><div class="progress"><span class="${d.color}" style="width:${p}%"></span></div><b>${p}%</b></div></td><td><strong>${d.daysLeft} hari</strong><small>menuju berangkat</small></td><td><span class="status ${d.color}">${d.status}</span></td></tr>`; }).join("") : `<tr><td colspan="6" class="empty">Tidak ada keberangkatan yang cocok dengan filter.</td></tr>`;
}
function renderPace(items) {
  const d = items[0] || data.departures[0], left=d.quota-d.sold, weeks=Math.max(Math.ceil(d.daysLeft/7)-1,1), target=Math.ceil(left/weeks), actual=2;
  el("paceContent").innerHTML = `<div class="pace-hero"><span>Kebutuhan saat ini</span><strong>${target} <small>jamaah / minggu</small></strong><p>agar kuota ${d.name} terpenuhi</p></div><div class="pace-stats"><div><span>Aktual minggu ini</span><strong>${actual}</strong></div><div><span>Target mingguan</span><strong>${target}</strong></div><div><span>Selisih</span><strong class="danger">-${Math.max(target-actual,0)}</strong></div></div><div class="pace-meter"><div><span>Progress minggu ini</span><b>${Math.min(Math.round(actual/target*100),100)}%</b></div><div class="progress large"><span class="amber" style="width:${Math.min(Math.round(actual/target*100),100)}%"></span></div></div><p class="pace-tip"><b>Rekomendasi:</b> fokuskan follow up pada 7 booking aktif untuk mengejar target.</p>`;
}
function renderPipeline() { const max=data.pipeline[0].value; el("pipeline").innerHTML=data.pipeline.map((p,i)=>`<div class="pipeline-row"><span>${p.label}</span><div><i style="width:${p.value/max*100}%;background:${p.color}"></i></div><strong>${p.value}</strong><small>${i?Math.round(p.value/data.pipeline[i-1].value*100)+'%':''}</small></div>`).join(""); }
function renderSources() { let angle=0; const stops=data.sources.map(s=>{const start=angle;angle+=s.pct*3.6;return `${s.color} ${start}deg ${angle}deg`}); el("donut").style.background=`conic-gradient(${stops.join(',')})`; el("sourceLegend").innerHTML=data.sources.map(s=>`<div><i style="background:${s.color}"></i><span>${s.label}</span><strong>${s.value}</strong><small>${s.pct}%</small></div>`).join(""); }
function renderFinance(){ const f=data.finance; el("financeContent").innerHTML=`<div class="finance-main"><span>Potensi Pendapatan</span><strong>${compact(f.revenue)}</strong><small>Dari seluruh jamaah terjual</small></div><div class="finance-progress"><div><span>Dana masuk</span><b>${f.progress}%</b></div><div class="progress large"><span class="green" style="width:${f.progress}%"></span></div></div><div class="finance-split"><div><span>Sudah diterima</span><strong>${compact(f.received)}</strong></div><div><span>Sisa piutang</span><strong>${compact(f.receivable)}</strong></div></div>`; }
function renderAlerts(){ el("alertsGrid").innerHTML=data.alerts.map(a=>`<article class="alert ${a.tone}"><span class="alert-icon">${a.icon}</span><div><h3>${a.title}</h3><p>${a.body}</p><button>${a.action} →</button></div></article>`).join(""); }
function renderChart(){const vals=data.trend,w=720,h=170,pad=20,max=Math.max(...vals)+3,pts=vals.map((v,i)=>[pad+i*(w-pad*2)/(vals.length-1),h-v/max*(h-25)]);const line=pts.map(p=>p.join(',')).join(' '), area=`${pad},${h} ${line} ${w-pad},${h}`;el("trendChart").innerHTML=`<defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#0B8F7C" stop-opacity=".25"/><stop offset="100%" stop-color="#0B8F7C" stop-opacity="0"/></linearGradient></defs>${[0,1,2,3].map(i=>`<line x1="20" y1="${25+i*45}" x2="700" y2="${25+i*45}" stroke="#e7ebf0"/>`).join('')}<polygon points="${area}" fill="url(#area)"/><polyline points="${line}" fill="none" stroke="#0B8F7C" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="#fff" stroke="#0B8F7C" stroke-width="3"><title>Minggu ${i+1}: ${vals[i]} jamaah</title></circle>`).join('')}${vals.map((_,i)=>`<text x="${pts[i][0]}" y="212" text-anchor="middle">M${i+1}</text>`).join('')}`;}
function refreshPeriodFilter(){const current=el("periodFilter").value;el("periodFilter").innerHTML='<option value="all">Semua Keberangkatan</option>'+data.departures.map(d=>`<option value="${d.id}">${d.name} — ${formatDate(d.date)}</option>`).join('');if([...el("periodFilter").options].some(o=>o.value===current))el("periodFilter").value=current;}
function persistPackages(){localStorage.setItem("andira_umroh_packages",JSON.stringify(data.departures));}
function showToast(message){el("toast").textContent=message;el("toast").classList.add("show");setTimeout(()=>el("toast").classList.remove("show"),2200);}
function renderMasterPackages(){el("packageCount").textContent=`${data.departures.length} paket tersimpan`;el("masterPackageTable").innerHTML=data.departures.map(d=>{const pct=Math.round(d.sold/d.quota*100);return `<tr><td><strong>${d.name}</strong><small>${d.notes||'—'}</small></td><td>${formatDate(d.date)}</td><td><strong>${rupiah(d.price||0)}</strong><small>per jamaah</small></td><td><strong>${d.quota}</strong><small>jamaah</small></td><td><div class="progress-row"><div class="progress"><span class="${d.color}" style="width:${pct}%"></span></div><b>${d.sold}</b></div></td><td><span class="package-status ${d.packageStatus==='Aktif'?'active':d.packageStatus==='Draft'?'draft':'closed'}">${d.packageStatus||'Aktif'}</span></td><td><div class="row-actions"><button onclick="editPackage(${d.id})">Edit</button><button class="delete" onclick="deletePackage(${d.id})">Hapus</button></div></td></tr>`}).join('');}
function openPackageForm(item){el("packageFormPanel").hidden=false;el("formTitle").textContent=item?'Edit Paket':'Tambah Paket Baru';el("packageId").value=item?.id||'';el("packageName").value=item?.name||'';el("packageDate").value=item?.date||'';el("packagePrice").value=item?.price||'';el("packageQuota").value=item?.quota||'';el("packageStatus").value=item?.packageStatus||'Aktif';el("packageNotes").value=item?.notes||'';el("packageName").focus();}
function closePackageForm(){el("packageFormPanel").hidden=true;el("packageForm").reset();}
window.editPackage=id=>openPackageForm(data.departures.find(d=>d.id===id));
window.deletePackage=id=>{const item=data.departures.find(d=>d.id===id);if(!item||!confirm(`Hapus paket ${item.name}?`))return;data.departures=data.departures.filter(d=>d.id!==id);persistPackages();refreshPeriodFilter();renderMasterPackages();render();showToast("Paket berhasil dihapus");};
function render(){const items=filteredDepartures();renderKPIs(items);renderDepartures(items);renderPace(items);}
refreshPeriodFilter();
["periodFilter","statusFilter"].forEach(id=>el(id).addEventListener("change",render));
el("menuButton").addEventListener("click",()=>el("sidebar").classList.toggle("open"));
const sectionTargets={keberangkatan:"keberangkatanSection",jamaah:"jamaahSection",penjualan:"penjualanSection",keuangan:"keuanganSection"};
document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));btn.classList.add("active");const section=btn.dataset.section;const master=section==='master-paket';el("masterView").hidden=!master;el("dashboardContent").hidden=master;if(master)renderMasterPackages();else if(sectionTargets[section])requestAnimationFrame(()=>el(sectionTargets[section]).scrollIntoView({behavior:"smooth",block:"start"}));else window.scrollTo({top:0,behavior:"smooth"});if(innerWidth<900)el("sidebar").classList.remove("open");}));
el("exportButton").addEventListener("click",()=>{window.print();});
el("newPackageButton").addEventListener("click",()=>openPackageForm());el("closeFormButton").addEventListener("click",closePackageForm);el("cancelFormButton").addEventListener("click",closePackageForm);
el("packageForm").addEventListener("submit",event=>{event.preventDefault();const id=Number(el("packageId").value);const existing=data.departures.find(d=>d.id===id);const quota=Number(el("packageQuota").value);if(existing&&quota<existing.sold){showToast(`Kuota minimal ${existing.sold}, sesuai jamaah terjual`);return;}const date=el("packageDate").value;const daysLeft=Math.max(Math.ceil((new Date(`${date}T00:00:00`)-new Date())/86400000),0);const item={id:id||Date.now(),name:el("packageName").value.trim(),date,price:Number(el("packagePrice").value),quota,sold:existing?.sold||0,booking:existing?.booking||0,daysLeft,status:existing?.status||'Kritis',packageStatus:el("packageStatus").value,notes:el("packageNotes").value.trim(),color:existing?.color||'red'};if(existing)Object.assign(existing,item);else data.departures.push(item);persistPackages();refreshPeriodFilter();renderMasterPackages();render();closePackageForm();showToast(existing?'Paket berhasil diperbarui':'Paket baru berhasil ditambahkan');});
render(); renderMasterPackages(); renderPipeline(); renderSources(); renderFinance(); renderAlerts(); renderChart();
